### ISSUE TITLE
B4 layout & grid is not compatible with animate

### ISSUE THREAD

**Issue by hduchesne** [pvollenweider/animate#3]
I created a B4 layout & grid content with an html <section\>, a container and a row and apply an animation on it.
The animate module create 2 <div\> wrapper with the same id :

1. one around the <section\>
2. a second around the cols

The result is, the hide a the second div wrapper because by default the opacity is 0
In the image below we can see the second <div\> (blue highlight) wrapper around the cols. The <div\> id is the same as the <div\> for line above.

![image](https://user-images.githubusercontent.com/55382113/72168206-fda4c380-33cc-11ea-9d04-1962f8bde079.png)

**Comment by pvollenweider** [comment]
Animate.css does not support cascading animations. Please report it on animate.css project https://github.com/daneden/animate.css

**Comment by hduchesne** [comment]
it is not a cascading from animate, but the Jahia animate wrapper which add 2 times the same animation on the B4 layout & grid. That is why we have the same div id.

**Comment by pvollenweider** [comment]
It's a B4 issue. Fixed here https://github.com/Jahia/bootstrap4/commit/23c71e5ec5d4d2004ef3be625556489b037327f7
